.nh
.TH jq-libs 1
.SH Setup
Clone the repository:

.EX
git clone https://github.com/brainwo/jq-libs.git
.EE

.PP
Import the library when invoking \fBjq\fR:

.EX
jq -L "path/to/cloned/git/repository" {...}
.EE

.PP
Optionally, you can set an ALIAS(1P)
\[la]https://man.archlinux.org/man/alias.1p\[ra] to \fBjq\fR\&.

.PP
Optionally, you can set a ZSH alias (zsh-lovers(1)
\[la]https://man.archlinux.org/man/zsh\-lovers.1\[ra]) to this README page and read it anytime using your favorite pager:

.EX
alias -g jq-libs="path/to/cloned/git/repository/jq-libs.1"
glow -p jq-libs
.EE

.SH Available libraries:
htmld
\[la]./htmld.jq\[ra]: The inverse of \fB@html\fR\&.

.EX
jq `include "htmld"; htmld`
   "This works if x &lt; y"
=> "This works if x < y"
.EE
