.TH "jq-libs" 1

.SH "Name"
.PP
jq\-libs \- Collection of jq modules

.SH "SETUP"
.PP
Clone the repository:
.RS
.PP
.nf
git clone https://github\.com/brainwo/jq\-libs\.git
.fi
.RE
.PP
Import the library when invoking `\f[CR]jq\fP`:
.RS
.PP
.nf
jq \-L "path/to/cloned/git/repository" {\.\.\.}
.fi
.RE
.PP
Optionally, you can set an ALIAS(1P)[1] to `\f[CR]jq\fP`\.
.sp
[1] https://man\.archlinux\.org/man/alias\.1p jq\-libs
.nf
.fi

.PP
Optionally, you can set a ZSH alias (zsh\-lovers(1)[2]) to this README
page and read it anytime using your favorite pager:
.sp
[2] https://man\.archlinux\.org/man/zsh\-lovers\.1 jq\-libs
.nf
.fi

.RS
.PP
.nf
alias \-g jq\-libs="path/to/cloned/git/repository/jq\-libs\.1"
man jq\-libs
.fi
.RE

.SH "AVAILABLE LIBRARIES"
.PP
htmld[3]: The inverse of `\f[CR]@html\fP`\.
.sp
[3] \./htmld\.jq jq\-libs
.nf
.fi

.RS
.PP
.nf
jq `include "htmld"; htmld`
   "This works if x &lt; y"
=> "This works if x < y"
.fi
.RE

.SH "FOR MAINTAINER"

.SS "Generate `\f[CR]jq-libs.1\fP` from `\f[CR]README.md\fP`:"
.PP
Use go\-md2man[4]\.
.sp
[4] https://github\.com/cpuguy83/go\-md2man jq\-libs
.nf
.fi

.RS
.PP
.nf
go\-md2man < README\.md > jq\-libs\.1
.fi
.RE

.SH "BUGS"
.PP
Report them here in https://github\.com/brainwo/jq\-libs/issues\.
